import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.tree.ParseTreeVisitor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class main {
    public static void main(String[] args) throws IOException{

	// we expect exactly one argument: the name of the input file
	if (args.length!=1) {
	    System.err.println("\n");
	    System.err.println("Impl Interpreter\n");
	    System.err.println("=================\n\n");
	    System.err.println("Please give as input argument a filename\n");
	    System.exit(-1);
	}
	String filename=args[0];

	// open the input file
	CharStream input = CharStreams.fromFileName(filename);
	    //new ANTLRFileStream (filename); // depricated
	
	// create a lexer/scanner
	hdlLexer lex = new hdlLexer(input);
	
	// get the stream of tokens from the scanner
	CommonTokenStream tokens = new CommonTokenStream(lex);
	
	// create a parser
	hdlParser parser = new hdlParser(tokens);
	
	// and parse anything from the grammar for "start"
	ParseTree parseTree = parser.start();

	// Construct an interpreter and run it on the parse tree
	Interpreter interpreter = new Interpreter();
	String result=interpreter.visit(parseTree);
	System.out.println("The result is: "+result);
    }
}

// We write an interpreter that implements interface
// "implVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Double.

class Interpreter extends AbstractParseTreeVisitor<String> implements hdlVisitor<String> {
	// todo - Java will complain that "Interpreter" does not in fact
	// implement "implVisitor" at the moment.

	@Override
	public String visitTerminal(TerminalNode node) {
		return node.getText(); // Return the text of the visited token
	}

	//add comment to negar
	public String visitStart(hdlParser.StartContext ctx) {
		System.out.println("Evaluating Start");
		//return "hello";


		String program = "<!DOCTYPE html>\n" +
				" <html><head><title> My Pretty Printer</title>\n" +
				" <script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n" +
				"<script type=\"text/javascript\" id=\"MathJax-script\"\n" +
				"async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js\">\n" +
				"</script></head><body>\n";
		program += "\n<h1>" + ctx.name_of_file.getText() + "</h1>\n";

		//ArrayList<String> insLen= (ArrayList<String>)ctx.ins;
		program += "\n<h2> Inputs </h2>\n";
		for (Token c : ctx.ins)
			program += c.getText() + " \n";

		program += "\n<h2> Outputs </h2>\n";
		for (Token c : ctx.outs)
			program += c.getText() + " ";

		program += "\n\n<h2> Latches </h2>\n";
		program += visit(ctx.lats);
		program += "\n<h2> Updates </h2>\n";
		program += visit(ctx.upds);

		program += "\n<h2> Simulation inputs </h2>\n";
		program += visit(ctx.sim);
		program += "\n</body></html>\n";

		System.out.println(program);

		return ctx.name_of_file.getText();
	}

	@Override
	public String visitLatchSection(hdlParser.LatchSectionContext ctx) {
		System.out.println("latches Section");
		int length = ctx.latches().size();

		String latches = "";
		for (int i = 0; i < length; i++) {
			latches += visit(ctx.latches().get(i));
		}
		//	System.out.println(latches);
		return latches;
	}

	@Override
	public String visitLatches(hdlParser.LatchesContext ctx) {
		String id1 = ctx.id1.getText();
		String id2 = ctx.id2.getText();
		return id1 + "&rarr;" + id2 + "<br>\n";
	}

	@Override
	public String visitUpdateSection(hdlParser.UpdateSectionContext ctx) {
		System.out.println("Update Section");
		int length = ctx.updates().size();

		String updates = "";
		for (int i = 0; i < length; i++) {
			updates += visit(ctx.updates().get(i));
		}
		//	System.out.println(latches);
		return updates;
	}

	@Override
	public String visitUpdates(hdlParser.UpdatesContext ctx) {
		String id = ctx.id.getText();
		return id + "&larr;" + visit(ctx.e) + "<br>\n";
	}

	@Override
	public String visitSimulateSection(hdlParser.SimulateSectionContext ctx) {
		String id = ctx.id.getText();
		return "<b>" + id + "</b>:" + ctx.e.getText() + "<br>";
	}

	@Override
	public String visitNot(hdlParser.NotContext ctx) {
		return "\\neg(" + visit(ctx.e) + ")";
	}

	@Override
	public String visitOr(hdlParser.OrContext ctx) {
		return visit(ctx.e1) + "\\vee(" + visit(ctx.e2) + ")";
	}

	@Override
	public String visitVar(hdlParser.VarContext ctx) {
		return ctx.id.getText();
	}

	@Override
	public String visitAnd(hdlParser.AndContext ctx) {
		return visit(ctx.e1) + "\\wedge(" + visit(ctx.e2) + ")";
	}

	@Override
	public String visitNum(hdlParser.NumContext ctx) {
		return ctx.n.getText();
	}

	@Override
	public String visitParen(hdlParser.ParenContext ctx) {

		return "(" + visit(ctx.e) + ")";
	}
}